### ISSUE TITLE
macOSX sierra, command not working

### ISSUE THREAD

**Issue by abhivanarase** [bcseda/BatteryCharge#1]
the `command: "pmset -g batt | grep \"%\" | awk 'BEGINN { FS = \";\" };{ print $3,$2 }' | sed -e 's/-I/I/' -e 's/-0//' -e 's/;//' -e 's/;//'"`
does not work as expected on mac osx sierra, suggested fix:
`pmset -g batt | grep \"%\" | awk 'BEGINN { FS = \";\" };{ print $3,$4 }' | sed -e 's/-I/I/' -e 's/-0//' -e 's/;//' -e 's/;//'`

**Comment by rowan-seda** [comment]
What value are you expecting? Is percentage not the value returned?

**Comment by abhivanarase** [comment]
`print $3,$2` is returning battery percent and id. Changing to `$3$4` seems to achieve what the script expects.
Here is the pmset command as run on sierra:

```
➜  ~ pmset -g batt
Now drawing from 'AC Power'
 -InternalBattery-0 (id=4128867)    100%; charged; 0:00 remaining present: true
```

**Comment by rowan-seda** [comment]
Your suggested change would cause difficulties with pmset output of prior versions of OSX. I have incorporated your suggestion with a check for placement of charging state output. Could you test the version on the dev branch in Sierra?

**Comment by abhivanarase** [comment]
`charge` is actually moved to the second term, so value[1] ends up having the charge percentage in it on sierra

```
➜  ~ pmset -g batt | grep "%" | awk 'BEGINN { FS = ";" };{ print $2,$3,$4 }' | sed -e 's/-I/I/' -e 's/-0//' -e 's/;//' -e 's/;//'
(id=4128867) 100% charged
```

**Comment by rowan-seda** [comment]
The dev branch should no longer depend on the order of the terms. Could you please test this on Sierra?

**Comment by abhivanarase** [comment]
yup, that works perfectly.

**Comment by abhivanarase** [comment]
The bolt logic seems to now be broken, the bolt is always displayed, regardless of state`discharging` `charging` or `charged`

**Comment by rowan-seda** [comment]
Apparently the ternary operator does not work in CoffeeScript. Please test the latest commit to dev.

**Comment by abhivanarase** [comment]
Yup that works, good to merge.
